export const demoRun = {
  runId: '2048',
  environment: 'Demo Environment · ENS + 0G + AXL',
  headerStatus: [
    { label: 'Verified', tone: 'success' as const },
    { label: 'AXL Live', tone: 'info' as const },
    { label: 'Trace Stored', tone: 'success' as const },
  ],
  lifecycleState: {
    Publish: 'done',
    Discover: 'done',
    Verify: 'done',
    Call: 'active',
    Trace: 'done',
    Report: 'done',
  } as const,
  stepDetails: {
    Publish: 'Manifest uploaded to 0G with capability index seeded.',
    Discover: 'Capability query resolved ENS tool identity.',
    Verify: 'Manifest hash, owner, version, and schema checked.',
    Call: 'Audit agent invoked remote node over AXL.',
    Trace: 'Request, response, and artifacts persisted to 0G.',
    Report: 'Final audit report references trace provenance.',
  },
  discovery: {
    requestedCapability: 'solidity-static-analysis',
    resolvedIdentity: 'scanner.audittool.eth',
    tool: 'solidity-pattern-scanner',
    optionalNode: 'test-case-suggester',
    capabilityMatches: '2 candidate tools, 1 preferred by version policy',
  },
  manifest: {
    uri: '0g://manifests/scanner/v1.2.0',
    version: '1.2.0',
    owner: '0xA51c...9E4f',
    schemaStatus: 'verified',
    ownerSignature: 'valid',
    compatibility: 'sdk ^0.1 compatible',
    hash: 'sha256:78f6d8d0ab1c4c1bc6ce4b7e2aa9fe5085a28489f8d4315fe37cbbbe7650f393',
  },
  invocation: {
    agent: 'Solidity Audit Agent',
    remoteNode: 'solidity-pattern-scanner',
    peer: 'axl://scanner-node-01',
    status: 'success',
    requestSummary: 'Contract source + policy profile + trace context',
    responseSummary: '3 findings returned with severity and evidence',
    findingsBadge: 'Structured response · findings: 3',
  },
  memory: {
    traceUri: '0g://traces/run-2048',
    inputHash: 'sha256:4f2bc4de8ac26a8b4d460a7dbb4348f6ab9c502e4f6128e9fd283f1828f0c6a1',
    outputHash: 'sha256:b6c8aa3a454b8f6c0aa90bf7254cc398d4473e4ce314cb7a41f0d991b29ea56b',
    artifactReference: '0g://artifacts/findings/run-2048.json',
    reportReference: '0g://reports/audit-run-2048.md',
    traceStatus: 'stored with provenance',
  },
  report: {
    findings: 3,
    severity: [
      { label: 'High', value: 1, tone: 'high' as const },
      { label: 'Medium', value: 1, tone: 'medium' as const },
      { label: 'Low', value: 1, tone: 'low' as const },
    ],
    traceReference: 'trace:run-2048',
    manifestVersion: 'scanner@1.2.0',
    summary: [
      'Unchecked external call path exposes a reentrancy window before state finalization.',
      'Owner-only emergency withdrawal lacks event emission, weakening incident forensics.',
      'Missing negative-path tests for paused-state transfers were suggested for the follow-up node.',
    ],
  },
};
